apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storagekeyref
  namespace: demo-staticsite
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${k8s_secret_store_name}
    kind: SecretStore
  target:
    name: ${k8s_storage_key_secret_name}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret#static-provisioning-parameters
        azurestorageaccountname: "${storage_account_name}"
        azurestorageaccountkey: "{{ `{{ .key }}` }}"
  data:
  - secretKey: key
    remoteRef:
      key: ${storage_key_secret_name}
