apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ${k8s_secret_store_name}
  namespace: demo-staticsite
spec:
  provider:
    azurekv:
      vaultUrl: ${vault_url}
      authType: WorkloadIdentity
      serviceAccountRef:
        name: ${k8s_service_account_name}