apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${k8s_service_account_name}
  namespace: demo-staticsite
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: ${client_id}
    azure.workload.identity/tenant-id: ${tenant_id}
automountServiceAccountToken: false
