apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://{{env.argocd_hostname}}
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/{{env.tenant_id}}/v2.0
    clientID: {{env.argocd_application_id}}
    clientSecret: $oidc.azure.clientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
