apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-secret-store
  namespace: argocd
spec:
  provider:
    azurekv:
      vaultUrl: {{env.key_vault_uri}}
      authType: WorkloadIdentity
      serviceAccountRef:
        name: workload-identity-cloud