apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-cloud
  namespace: argocd
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{env.core_workload_identity_client_id}}
    azure.workload.identity/tenant-id: {{env.tenant_id}}
automountServiceAccountToken: false
