apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argocd-secret-store
    kind: SecretStore
  target:
    name: argocd-secret
    template:
      engineVersion: v2
      data:
        tls.crt: "{{ .cert }}"
        tls.key: "{{ .key }}"
        oidc.azure.clientSecret: "{{ .clientSecret }}"
        server.secretKey: "{{ .serverSecret }}"
  data:
  - secretKey: cert
    remoteRef:
      key: cluster-ssl-cert
  - secretKey: key
    remoteRef:
      key: cluster-ssl-key
  - secretKey: clientSecret
    remoteRef:
      key: argocd-application-client-secret
  - secretKey: serverSecret
    remoteRef:
      key: argocd-server-secret
