apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: 'false'
  users.anonymous.enabled: 'false'
  statusbadge.enabled: 'true'
  kustomize.buildOptions: --enable-helm
  dex.config: ""
