apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
resources:
- argocd-secret.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.9/manifests/install.yaml

patches:
- path: argocd-cm.yaml
- path: argocd-rbac-cm.yaml
