apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tls-vault
  namespace: ingress-nginx
spec:
  provider:
    azurekv:
      vaultUrl: {{env.key_vault_uri}}
      authType: WorkloadIdentity
      serviceAccountRef:
        name: workload-identity-cloud