# THIS FILE IS MANAGED BY AUTOMATION!
# IF YOU WANT TO MAKE CHANGES, EDIT THE TEMPLATE AND RE-RUN THE AUTOMATION
# GO TO `iac-kubernetes/manifest_templates.ipynb` TO FIND THE AUTOMATION

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: argocd
automountServiceAccountToken: false
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-system
automountServiceAccountToken: false
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: external-secrets
automountServiceAccountToken: false
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ingress-nginx
automountServiceAccountToken: false
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: azure-workload-identity-system
automountServiceAccountToken: false
---
