# THIS FILE IS MANAGED BY TERRAFORM!
# IF YOU WANT TO MAKE CHANGES, EDIT `azure/kubernetes_templates` INSTEAD OF `kubernetes/templates` !!!

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-kv
  namespace: demo-staticsite
spec:
  provider:
    azurekv:
      vaultUrl: https://mydemokeyvault.vault.azure.net/
      authType: WorkloadIdentity
      serviceAccountRef:
        name: workload-identity-demo-staticsite