# THIS FILE IS MANAGED BY TERRAFORM!
# IF YOU WANT TO MAKE CHANGES, EDIT `azure/kubernetes_templates` INSTEAD OF `kubernetes/templates` !!!

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storagekeyref
  namespace: demo-staticsite
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: demo-kv
    kind: SecretStore
  target:
    name: storagekey
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-nfs%2Csecret#static-provisioning-parameters
        azurestorageaccountname: "mydemokeyvault"
        azurestorageaccountkey: "{{ .key }}"
  data:
  - secretKey: key
    remoteRef:
      key: storagekey
