# THIS FILE IS MANAGED BY TERRAFORM!
# IF YOU WANT TO MAKE CHANGES, EDIT `azure/kubernetes_templates` INSTEAD OF `kubernetes/templates` !!!

apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-demo-staticsite
  namespace: demo-staticsite
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 555-555-555-5555
    azure.workload.identity/tenant-id: 555-555-555-5555
automountServiceAccountToken: false
