# THIS FILE IS MANAGED BY AUTOMATION!
# IF YOU WANT TO MAKE CHANGES, EDIT THE TEMPLATE AND RE-RUN THE AUTOMATION
# GO TO `iac-kubernetes/manifest_templates.ipynb` TO FIND THE AUTOMATION
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd-secret-store
  namespace: argocd
spec:
  provider:
    azurekv:
      vaultUrl: https://my-cluster-dev-1-kv.vault.azure.net/
      authType: WorkloadIdentity
      serviceAccountRef:
        name: workload-identity-cloud