# THIS FILE IS MANAGED BY AUTOMATION!
# IF YOU WANT TO MAKE CHANGES, EDIT THE TEMPLATE AND RE-RUN THE AUTOMATION
# GO TO `iac-kubernetes/manifest_templates.ipynb` TO FIND THE AUTOMATION
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-cloud
  namespace: argocd
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 555-555-555-555
    azure.workload.identity/tenant-id: 555-555-555-555
automountServiceAccountToken: false