{% for namespace in project.apps.values()|map(attribute='k8s_namespace')|unique %}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: restricted
  name: {{ namespace }}
---

{% endfor %}

{%- if project.name == "cluster-stuff" %}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: restricted
  name: default
{%- endif %}